Repository Software-Engineering-2-group-E/LiRA-Map, pull requests merged in 2022-12, with the labels that each got.

#141 MUI-fied Road Measurements
  client/package-lock.json
  client/package.json
  client/src/components/RoadMeasurements/MeasurementTypes.tsx
  client/src/components/RoadMeasurements/OptionsSelector.tsx
  client/src/components/RoadMeasurements/RideCards.tsx
  client/src/components/RoadMeasurements/RideCardsA.tsx
  client/src/components/RoadMeasurements/RideDetails.tsx
  client/src/components/RoadMeasurements/RideDetailsA.tsx
  client/src/components/RoadMeasurements/RideListComponent.tsx
  client/src/components/RoadMeasurements/RideListComponentDetails.tsx
  client/src/components/RoadMeasurements/Rides.tsx
  client/src/components/RoadMeasurements/RidesMap.tsx
  client/src/components/RoadMeasurements/RidesPopup.tsx
  client/src/context/MeasurementsContext.tsx
  client/src/context/MetasContext.tsx
  client/src/models/index.ts
  client/src/models/ride.ts
  client/src/pages/RoadMeasurement.tsx
  client/src/queries/measurements.ts
  server-nest/src/measurements/measurements.json
Labels: ui-overhaul

#138 125 us rework road measurements graph
  client/package-lock.json
  client/package.json
  client/src/components/Map/MapWrapper.tsx
  client/src/components/RoadMeasurements/MeasurementTypes.tsx
  client/src/components/RoadMeasurements/RideCards.tsx
  client/src/components/RoadMeasurements/RideCardsA.tsx
  client/src/components/RoadMeasurements/RideDetailsA.tsx
  client/src/components/RoadMeasurements/RideGraphCard.tsx
  client/src/components/RoadMeasurements/Rides.tsx
  client/src/pages/RoadMeasurement.tsx
  server-nest/src/measurements/measurements.json
Labels: enhancement, ui-overhaul

#147 Layout and sidebar improvements
  client/src/components/Page.tsx
  client/src/components/RoadMeasurements/RideGraphCard.tsx
  client/src/components/RoadMeasurements/Rides.tsx
  client/src/components/RoadMeasurements/RidesMap.tsx
  client/src/components/animate/MotionViewport.tsx
  client/src/components/nav-section/vertical/index.tsx
  client/src/context/CollapseDrawerContext.tsx
  client/src/layouts/dashboard/header/AccountPopover.tsx
  client/src/layouts/dashboard/header/index.tsx
  client/src/layouts/dashboard/index.tsx
  client/src/layouts/dashboard/navbar/NavbarVertical.tsx
  client/src/pages/RoadCondition.tsx
  client/src/pages/RoadMeasurement.tsx
  client/src/pages/Settings.tsx
  client/src/theme/index.tsx
  client/src/utils/getFontValue.ts
Labels: bug, enhancement, ui-overhaul

#150 Export trip data to CSV file
  client/src/components/RoadMeasurements/RideGraphCard.tsx
Labels: enhancement

#153 Fix Road Measurements Graph window scaling
  client/src/components/RoadMeasurements/RideGraphCard.tsx
Labels: bug, enhancement

#155 Collapsible Graph Card
  client/src/components/RoadMeasurements/RideGraphCard.tsx
Labels: enhancement

#156 Waypoint in trip is connected to point on graph
  client/src/components/Map/MetadataPath.tsx
  client/src/components/RoadMeasurements/RideGraphCard.tsx
  client/src/components/RoadMeasurements/Rides.tsx
  client/src/context/MarkerContext.tsx
Labels: enhancement

#162 Collapsible trip selector
  client/src/components/RoadMeasurements/RidesPopup.tsx
Labels: enhancement

#164 Hotfix to only fetch rides with distance further than 100 meters
  server-nest/src/rides/rides.service.ts
Labels: bug

#167 Margin on dashboard fix and pages commented out from navigation
  client/src/layouts/dashboard/navbar/NavConfig.tsx
  client/src/pages/Dashboard.tsx
Labels: bug

#172 Moved the Road Profile into a collapsible card component so that the …
  client/src/components/RoadProfiles/RoadProfile.tsx
  client/src/pages/RoadCondition.tsx
Labels: enhancement

#178 Display measurements with multiple values in graph
  client/src/components/RoadMeasurements/RideGraphCard.tsx
  client/src/components/RoadMeasurements/Rides.tsx
  client/src/components/RoadMeasurements/RidesMap.tsx
  client/src/models/path.ts
  client/src/queries/rides.ts
  server-nest/src/measurements/measurements.service.ts
  server-nest/src/models.ts
  server-nest/src/rides/rides.controller.ts
  server-nest/src/rides/rides.service.ts
Labels: enhancement

#171 Added Managed Roads page
  client/src/components/Dashboard/CriticalRoadsTable.tsx
  client/src/components/Map/constants.ts
  client/src/components/RoadConditions/ConditionsMap.tsx
  client/src/components/RoadProfiles/CheckboxList.tsx
  client/src/components/RoadProfiles/RoadProfile.tsx
  client/src/layouts/dashboard/navbar/NavConfig.tsx
  client/src/pages/ManagedRoads.tsx
  client/src/pages/RoadCondition.tsx
  client/src/routes/index.tsx
Labels: ui-overhaul

#176 Fix Sign Up URL
  client/src/queries/fetch.tsx
Labels: bug

#179 Adjust number of data points in Road Measurement Graph
  client/package-lock.json
  client/package.json
  client/src/components/RoadMeasurements/RideGraphCard.tsx
Labels: enhancement

#181 Fix Road Profile & Managed Roads non-unique key error
  client/src/components/RoadProfiles/RoadProfile.tsx
  client/src/pages/ManagedRoads.tsx
Labels: bug

#183 Close account popover menu when a menu item has been clicked
  client/src/layouts/dashboard/header/AccountPopover.tsx
Labels: bug

#191 Feature/code cleanup
  client/src/components/RoadMeasurements/MeasurementTypes.tsx
  client/src/components/RoadMeasurements/OptionsSelector.tsx
  client/src/components/RoadMeasurements/Popup/PopupWrapper.tsx
  client/src/components/RoadMeasurements/Popup/useMeasPopup.tsx
  client/src/components/RoadMeasurements/RideCards.tsx
  client/src/components/RoadMeasurements/RideDetails.tsx
  client/src/components/RoadMeasurements/RideGraphCard.tsx
  client/src/components/RoadMeasurements/RideListComponent.tsx
  client/src/components/RoadMeasurements/RideListComponentDetails.tsx
  client/src/components/RoadMeasurements/Rides.tsx
  client/src/components/RoadMeasurements/RidesPopup.tsx
  client/src/layouts/dashboard/header/index.tsx
  client/src/layouts/dashboard/index.tsx
  client/src/routes/index.tsx
  server-nest/src/app.dto.ts
  server-nest/src/app.module.ts
  server-nest/src/database.ts
  server-nest/src/energy/energy.controller.ts
  server-nest/src/energy/energy.db.ts
  server-nest/src/energy/energy.dto.ts
  server-nest/src/energy/energy.math.ts
  server-nest/src/energy/energy.service.ts
  server-nest/src/main.ts
  server-nest/src/measurements/measurements.controller.ts
  server-nest/src/measurements/measurements.service.ts
  server-nest/src/rides/rides.service.ts
Labels: technical-tasks
