Repository Software-Engineering-2-group-E/LiRA-Map, pull requests merged in 2022-11, with the labels that each got.

#101 Implement Figma Settings
  client/src/components/MaterialUISwitch.tsx
  client/src/layouts/dashboard/header/AccountPopover.tsx
  client/src/pages/Settings.tsx
  client/src/routes/index.tsx
  server-nest/package-lock.json
Labels: ui-overhaul

#110 Implemented dark theme for OSM component
  client/src/components/Map/MapWrapper.tsx
Labels: enhancement, ui-overhaul

#108 Implement Figma User Dashboard
  client/src/components/Dashboard/CriticalRoadsTable.tsx
  client/src/components/Dashboard/RoadConditionsChart.tsx
  client/src/layouts/dashboard/navbar/NavConfig.tsx
  client/src/pages/Dashboard.tsx
  client/src/routes/index.tsx
Labels: ui-overhaul

#119 Fix Road Conditions visualizations
  client/src/components/RoadConditions/ConditionsGraph.tsx
  client/src/components/RoadConditions/ConditionsMap.tsx
  client/src/pages/RoadCondition.tsx
  client/src/queries/conditions.ts
Labels: bug, visualization

#124 Fix Signup link to Login page
  client/src/pages/Signup.tsx
Labels: bug

#120 Fix map marker
  client/src/components/Map/MetadataPath.tsx
Labels: bug

#126 Feature/84 visual identity pwa
  client/public/favicon.ico
  client/public/logo_144.png
  client/public/manifest.json
Labels: enhancement
